alias tmux="tmux -2"
alias run-dc-ngrok="dc run --service-ports --rm ngrok"
alias run-dc-web="aws-vault exec dev-lee-instance -- dc up --build web"
alias run-dc-web-nodebug="DEBUG=false aws-vault exec dev-lee-instance -- dc up --build web"
alias run-dc-web-jit="JIT_ASSETS=true aws-vault exec dev-lee-instance -- dc up --build web"
alias run-dc-dd="aws-vault exec dev-lee-instance -- dc up --build ddagent"
alias run-dc-worker="aws-vault exec dev-lee-instance -- dc up --build worker"
alias run-dc-command="dc run web python -m cloudsmith $@"
alias run-dc-shell="run-command shell_plus $@"
alias run-dc-makemigrations="run-command makemigrations $@"
alias run-dc-migrate="run-command migrate $@"
alias run-dc-bash="dc run --rm web bash"
